---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-app-customer-analytics
  namespace: analytics-team
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-app-customer-analytics
  namespace: analytics-team
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-app-customer-analytics
  namespace: analytics-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-app-customer-analytics
subjects:
- kind: ServiceAccount
  name: spark-app-customer-analytics
  namespace: analytics-team