[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-lib"
version = "0.1.0"
description = "A library for dependency testing"
authors = [{ name = "Chen" }]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src/python"]
